before_install: 
  chmod +x gradlew 
language: android
android:
  components:
    - build-tools-27.0.3
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - sys-img-armeabi-v7a-android-26

script:
    - ./gradlew test
    - ./gradlew test jacocoTestReport
    - sonar-scanner
    # - ./gradlew sonarqube -Dsonar.organization=christianwuggenig-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=01aaf8116a2dd110eb3d6d28fdbe33c891d3f500 -Dsonar.branch.name=master

addons:
  sonarcloud:
    organization: "christianwuggenig-github"
    token:
      secure: 01aaf8116a2dd110eb3d6d28fdbe33c891d3f500
